In [3]:
import numpy as np

# 1. 创建一个 3x4 的二维数组，元素为 1 到 12 的整数
array = np.arange(1, 13).reshape(3, 4)

# 打印数组的形状、维度和数据类型
print("数组的形状:", array.shape)
print("数组的维度:", array.ndim)
print("数组的数据类型:", array.dtype)

# 2. 将数组元素乘以 2，并打印结果
array_multiplied = array * 2
print("\n数组元素乘以 2 的结果:\n", array_multiplied)

# 3. 将数组重塑为 4x3 的形状，并打印新数组
array_reshaped = array.reshape(4, 3)
print("\n重塑为 4x3 的数组:\n", array_reshaped)

数组的形状: (3, 4)
数组的维度: 2
数组的数据类型: int32

数组元素乘以 2 的结果:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

重塑为 4x3 的数组:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
