In [1]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]])

# 任务 1：提取第 2 行
print("第 2 行所有元素:", array[1, :])

# 任务 2：提取第 3 列
print("第 3 列所有元素:", array[:, 2])

# 任务 3：提取子数组（第 1、2 行和第 2、3 列）
print("子数组（第 1、2 行和第 2、3 列）:\n", array[0:2, 1:3])

# 任务 4：将大于 10 的元素替换为 0
array[array > 10] = 0
print("替换大于 10 元素为 0 后的数组:\n", array)

第 2 行所有元素: [5 6 7 8]
第 3 列所有元素: [ 3  7 11 15]
子数组（第 1、2 行和第 2、3 列）:
 [[2 3]
 [6 7]]
替换大于 10 元素为 0 后的数组:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10  0  0]
 [ 0  0  0  0]]
