In [1]:
import numpy as np

# 创建数组
A = np.arange(1, 7).reshape(3, 2)
B = np.array([10, 20])

# 任务一：广播加法
add_result = A + B

# 任务二：广播乘法
mul_result = A * B

# 任务三：行与 B 的点积
dot_result = np.dot(A, B)

# 打印结果
print("数组 A:\n", A)
print("数组 B:", B)
print("\nA + B（广播后）:\n", add_result)
print("A * B（广播后）:\n", mul_result)
print("A 每一行与 B 的点积结果:", dot_result)

数组 A:
 [[1 2]
 [3 4]
 [5 6]]
数组 B: [10 20]

A + B（广播后）:
 [[11 22]
 [13 24]
 [15 26]]
A * B（广播后）:
 [[ 10  40]
 [ 30  80]
 [ 50 120]]
A 每一行与 B 的点积结果: [ 50 110 170]
